ROOT_DIR = ../../../..
PACKAGE_NAME = artisynth.models.tubesounds

JAVA_SUBDIRS =

PACKAGE_JAVA_FILES = 

default: build

r:
	java artisynth.models.tubesounds.VTNTDemo  .17 44100 .10  8 12

r5:
	java artisynth.models.tubesounds.VTDemo 5  .17 44100

r2:
	java artisynth.models.tubesounds.VTDemo2  .17 44100

a:
	java artisynth.models.tubesounds.AirwayMesh

-include $(ROOT_DIR)/Makefile.base
